---
# required vars:
#   gpg_key_src - GPG key to copy and import
#   gpg_key_dest - where to store the key
#   gnupghome - same semantics as GNUPGHOME environment variable

- name: "Copy {{ gpg_key_src }} GPG key"
  ansible.builtin.copy:
    src: "{{ gpg_key_src }}"
    dest: "{{ gpg_key_dest }}"
  register: gpg_key

- name: "Import {{ gpg_key_src }} GPG key"
  command:
    cmd: "gpg --import {{ gpg_key_dest }}"
  environment:
    GNUPGHOME: "{{ gnupghome }}"
  when: gpg_key.changed
